
FROM mongo:3.6.8

COPY ./mvp /mvp

# Khởi tạo db với file dữ liệu trong mvp
COPY ./entrypoint_mongo.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

EXPOSE 27017

ENTRYPOINT /entrypoint.sh

CMD mongod
