- hosts: all
  tasks:
    - name: Deploy all project production on server
      copy:
        src: "{{ item }}"
        dest: /home/vunm/telegramBot/
      with_items:
        - ../../StudyEnglish
      become: yes
